# Generated by Django 4.1.7 on 2023-03-12 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_days', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'db_table': 'days',
            },
        ),
        migrations.AlterField(
            model_name='savings',
            name='days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='savings.days'),
        ),
    ]
